### ISSUE TITLE
Question about Notices

### ISSUE THREAD

**Issue by joelataylor** [petermolnar/wp-common#3]
Is the plugin options page (and other pages) supposed to look like the attached image???

![screen shot 2015-02-20 at 8 55 56 am](https://cloud.githubusercontent.com/assets/119508/6287280/59076d28-b8de-11e4-8827-742cc5fd0669.png)

**Comment by petermolnar** [comment]
That looks like you have a debug system installed which was triggered since I send an E_USER_WARNING if there are things needed to be fixed.

So if you have a debug system, then the answer is yes.

**Comment by joelataylor** [comment]
Hi @petermolnar - thanks for the quick reply! I updated the image, and it looks like it's now just reporting a Notice (I have Xdebug installed) - is the plugin telling me to do something here?

**Comment by petermolnar** [comment]
Yep, search for:
"Warning: Advanced cache file is yet to be generated,"

**Comment by petermolnar** [comment]
also, the many messages indicates that WP_DEBUG is turned on.

**Comment by joelataylor** [comment]
Yeh, I have WP_DEBUG on. I'll just comment that notification line for now. Thanks for the plugin and feedback!
